/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Process is alive */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Liveness']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/readyz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness (Postgres, Redis, MinIO reachable) */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Ready to serve traffic */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Readiness']
          }
        }
        /** @description Not ready */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Readiness']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/plans': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List pricing plans */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Plans ordered by price */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              items: components['schemas']['Plan'][]
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create an account on the Free plan */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string
            password: string
            display_name?: string | null
          }
        }
      }
      responses: {
        /** @description Account created, session issued */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Session']
          }
        }
        409: components['responses']['Error']
        422: components['responses']['Error']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Exchange credentials for a JWT */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            email: string
            password: string
          }
        }
      }
      responses: {
        /** @description Session issued */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Session']
          }
        }
        401: components['responses']['Error']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Profile, plan and usage this month */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Current user */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Me']
          }
        }
        401: components['responses']['Error']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/images': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List the user's images, newest first */
    get: {
      parameters: {
        query?: {
          cursor?: string
          limit?: number
          /** @description Filename search */
          q?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description One page of images */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              items: components['schemas']['Image'][]
              next_cursor: string | null
            }
          }
        }
      }
    }
    put?: never
    /**
     * Upload an image (JPEG, PNG or WebP)
     * @description Size and resolution are limited by the plan. Metadata (EXIF/GPS) is stripped.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'multipart/form-data': {
            /** Format: binary */
            file: string
          }
        }
      }
      responses: {
        /** @description Stored */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Image']
          }
        }
        413: components['responses']['Error']
        415: components['responses']['Error']
        422: components['responses']['Error']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/images/{imageId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        imageId: string
      }
      cookie?: never
    }
    /** Image detail with a presigned URL of the original */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          imageId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Image */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Image']
          }
        }
        404: components['responses']['Error']
      }
    }
    put?: never
    post?: never
    /** Delete an image and all of its results */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          imageId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        404: components['responses']['Error']
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/presets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** System presets followed by the user's custom presets */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Presets */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              items: components['schemas']['Preset'][]
            }
          }
        }
      }
    }
    put?: never
    /** Save a custom preset */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            name: string
            pipeline: components['schemas']['Pipeline']
          }
        }
      }
      responses: {
        /** @description Saved */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Preset']
          }
        }
        409: components['responses']['Error']
        422: components['responses']['Error']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/presets/{presetId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        presetId: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete a custom preset */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          presetId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        404: components['responses']['Error']
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Render an image with a pipeline (checks quota, enqueues) */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            image_id: string
            pipeline: components['schemas']['Pipeline']
          } & components['schemas']['OutputOptions']
        }
      }
      responses: {
        /** @description Queued */
        202: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Job']
          }
        }
        404: components['responses']['Error']
        422: components['responses']['Error']
        429: components['responses']['Error']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/jobs/{jobId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        jobId: string
      }
      cookie?: never
    }
    /** Job status; result URLs once done */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          jobId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Job */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Job']
          }
        }
        404: components['responses']['Error']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/batches': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Apply one pipeline to many images (one job per image) */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            image_ids: string[]
            pipeline: components['schemas']['Pipeline']
          } & components['schemas']['OutputOptions']
        }
      }
      responses: {
        /** @description Queued */
        202: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Batch']
          }
        }
        403: components['responses']['Error']
        422: components['responses']['Error']
        429: components['responses']['Error']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/batches/{batchId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        batchId: string
      }
      cookie?: never
    }
    /** Batch progress with per-image status */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          batchId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Batch */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Batch']
          }
        }
        404: components['responses']['Error']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/batches/{batchId}/download': {
    parameters: {
      query?: never
      header?: never
      path: {
        batchId: string
      }
      cookie?: never
    }
    /** ZIP of all finished results */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          batchId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description ZIP archive */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/zip': string
          }
        }
        409: components['responses']['Error']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api-keys': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List API keys (Business plan) */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Keys (the secret is never returned again) */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              items: components['schemas']['APIKey'][]
            }
          }
        }
        403: components['responses']['Error']
      }
    }
    put?: never
    /** Create an API key; the plaintext key is shown once */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            label?: string | null
          }
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CreatedAPIKey']
          }
        }
        403: components['responses']['Error']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api-keys/{keyId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        keyId: string
      }
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Revoke an API key */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          keyId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Revoked */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        404: components['responses']['Error']
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @enum {string} */
    ErrorCode:
      | 'VALIDATION_ERROR'
      | 'UNAUTHORIZED'
      | 'FORBIDDEN'
      | 'NOT_FOUND'
      | 'CONFLICT'
      | 'QUOTA_EXCEEDED'
      | 'FILE_TOO_LARGE'
      | 'UNSUPPORTED_FORMAT'
      | 'RATE_LIMITED'
      | 'UNAVAILABLE'
      | 'INTERNAL'
    ErrorBody: {
      error: {
        code: components['schemas']['ErrorCode']
        message: string
      }
    }
    Liveness: {
      status: string
      node: string
    }
    Readiness: {
      /** @enum {string} */
      status: 'ready' | 'not_ready'
      node: string
      checks: {
        [key: string]: string
      }
    }
    Plan: {
      code: string
      name: string
      /** @description null means unlimited */
      monthly_quota: number | null
      max_file_mb: number
      max_resolution: number
      max_batch_size: number
      watermark: boolean
      api_access: boolean
      price_idr: number
    }
    User: {
      /** Format: uuid */
      id: string
      email: string
      display_name: string | null
      /** Format: date-time */
      created_at: string
    }
    Usage: {
      /** Format: date-time */
      period: string
      jobs_count: number
      bytes_in: number
    }
    Session: {
      token: string
      /** Format: date-time */
      expires_at: string
      user: components['schemas']['User']
    }
    Me: {
      user: components['schemas']['User']
      plan: components['schemas']['Plan']
      usage: components['schemas']['Usage']
    }
    Image: {
      /** Format: uuid */
      id: string
      filename: string
      /** @enum {string} */
      mime_type: 'image/jpeg' | 'image/png' | 'image/webp'
      size_bytes: number
      width: number
      height: number
      /** Format: date-time */
      created_at: string
      /** Format: date-time */
      expires_at: string | null
      /** @description Presigned URL of the original (short-lived) */
      url: string
      latest_job: null | {
        /** Format: uuid */
        id: string
        status: components['schemas']['JobStatus']
        result_url: string | null
      }
    }
    /** @description One step of a pipeline. Fields depend on `op`. */
    Operation: {
      /** @enum {string} */
      op:
        | 'preset'
        | 'brightness'
        | 'contrast'
        | 'saturation'
        | 'temperature'
        | 'blur'
        | 'sharpen'
        | 'vignette'
        | 'rotate'
        | 'flip'
        | 'resize'
      /**
       * @description preset only
       * @enum {string}
       */
      name?:
        'grayscale' | 'sepia' | 'vintage' | 'warm' | 'cool' | 'vivid' | 'noir' | 'fade' | 'invert'
      /**
       * @description brightness/contrast/saturation 0..2, temperature -100..100, blur 0..20,
       *     sharpen 0..3, vignette 0..1
       */
      value?: number
      /**
       * @description rotate only
       * @enum {integer}
       */
      angle?: 90 | 180 | 270
      /**
       * @description flip only
       * @enum {string}
       */
      direction?: 'h' | 'v'
      /** @description resize only */
      max_width?: number
      /** @description resize only */
      max_height?: number
    }
    Pipeline: {
      /** @enum {integer} */
      version: 1
      operations: components['schemas']['Operation'][]
    }
    Preset: {
      /** Format: uuid */
      id: string
      name: string
      pipeline: components['schemas']['Pipeline']
      is_system: boolean
      /** Format: date-time */
      created_at: string
    }
    /** @enum {string} */
    OutputFormat: 'jpeg' | 'png' | 'webp'
    OutputOptions: {
      output_format?: components['schemas']['OutputFormat']
      /** @default 90 */
      output_quality: number
    }
    /** @enum {string} */
    JobStatus: 'queued' | 'processing' | 'done' | 'failed'
    Job: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      image_id: string
      /** Format: uuid */
      batch_id: string | null
      status: components['schemas']['JobStatus']
      pipeline: components['schemas']['Pipeline']
      output_format: components['schemas']['OutputFormat']
      output_quality: number
      attempts: number
      /** @description Worker node that processed the job */
      worker_id: string | null
      error: string | null
      /** Format: date-time */
      created_at: string
      /** Format: date-time */
      started_at: string | null
      /** Format: date-time */
      finished_at: string | null
      result_url: string | null
      download_url: string | null
    }
    BatchJob: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      image_id: string
      filename: string
      status: components['schemas']['JobStatus']
      error: string | null
      worker_id: string | null
      result_url: string | null
      download_url: string | null
    }
    Batch: {
      /** Format: uuid */
      id: string
      pipeline: components['schemas']['Pipeline']
      total_jobs: number
      queued: number
      processing: number
      done: number
      failed: number
      finished: boolean
      /** Format: date-time */
      created_at: string
      jobs: components['schemas']['BatchJob'][]
    }
    APIKey: {
      /** Format: uuid */
      id: string
      label: string | null
      /** Format: date-time */
      last_used_at: string | null
      /** Format: date-time */
      revoked_at: string | null
      /** Format: date-time */
      created_at: string
    }
    CreatedAPIKey: components['schemas']['APIKey'] & {
      /** @description Plaintext key */
      key: string
    }
  }
  responses: {
    /** @description Error */
    Error: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorBody']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
